# Generated by Django 6.0.6 on 2026-07-01 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadRepuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_unico', models.CharField(max_length=100, unique=True)),
                ('codigo_barras', models.CharField(max_length=100, unique=True)),
                ('qr', models.ImageField(blank=True, null=True, upload_to='qr/')),
                ('estado', models.CharField(choices=[('NUEVA', 'Nueva'), ('FUNCIONAL', 'Funcional'), ('USADA', 'Usada'), ('DESARMADA', 'Desarmada'), ('DEFECTUOSA', 'Defectuosa')], default='NUEVA', max_length=20)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('anaquel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.anaquel')),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='almacen.repuesto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('repuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.repuesto')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='almacen.unidadrepuesto')),
            ],
        ),
    ]
