# Generated by Django 6.0.6 on 2026-07-01 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_unidadrepuesto_movimientoinventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadrepuesto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadrepuesto',
            name='codigo_unico',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
