# Generated by Django 6.0.6 on 2026-07-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0003_alter_unidadrepuesto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='stock_actual',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
