# Generated by Django 6.0.6 on 2026-07-02 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_repuesto_stock_actual'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='anaquel_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_entrada', to='almacen.anaquel'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='anaquel_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_salida', to='almacen.anaquel'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRASLADO', 'Traslado')], max_length=20),
        ),
    ]
