# Generated by Django 6.0.6 on 2026-07-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_movimientoinventario_anaquel_destino_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteRetirado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='almacen.unidadrepuesto')),
            ],
        ),
        migrations.CreateModel(
            name='BoardRegistroFotografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('frontal', models.ImageField(upload_to='boards/frontal/')),
                ('trasera', models.ImageField(upload_to='boards/trasera/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='almacen.unidadrepuesto')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('unidad', 'version')},
            },
        ),
    ]
