# Generated by Django 6.0.6 on 2026-07-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0006_componenteretirado_boardregistrofotografico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardregistrofotografico',
            name='version',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
