# Generated by Django 6.0.6 on 2026-07-07 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0007_alter_boardregistrofotografico_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repuesto',
            name='marca',
        ),
        migrations.AlterField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='almacen.marca'),
        ),
    ]
