# Generated by Django 6.0.6 on 2026-07-07 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0008_remove_repuesto_marca_alter_modelo_marca'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='repuesto',
            constraint=models.UniqueConstraint(fields=('modelo', 'tipo', 'referencia'), name='uk_repuesto_modelo_tipo_referencia'),
        ),
    ]
