# Generated by Django 6.0.6 on 2026-07-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0009_repuesto_uk_repuesto_modelo_tipo_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefijo', models.CharField(max_length=10, unique=True)),
                ('ultimo_numero', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='unidadrepuesto',
            name='qr',
        ),
        migrations.AddField(
            model_name='unidadrepuesto',
            name='imagen_codigo_barras',
            field=models.ImageField(blank=True, null=True, upload_to='codigos_barras/'),
        ),
    ]
