# Generated by Django 6.0.6 on 2026-07-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_correlativo_remove_unidadrepuesto_qr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='repuesto',
            name='imagen_codigo_barras',
            field=models.ImageField(blank=True, null=True, upload_to='codigos_barras_repuesto/'),
        ),
    ]
