# Generated by Django 6.0.6 on 2026-07-24 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_repuesto_codigo_barras_repuesto_imagen_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='codigo',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
