# Generated by Django 6.0.6 on 2026-09-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_repuesto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
