from .marca import *
from .modelo import *
from .tipo_repuesto import *
from .anaquel import *
from .repuesto import *
from .unidad_repuesto import *
from .movimiento import *
from .board_registro_fotografico import *
from .componente_retirado import *
from .correlativo import *